######################################################################
#
# File name : ad9361_test_top_compile.do
# Created on: Tue Nov 12 16:39:25 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -work xil_defaultlib  "+incdir+../../../../ad9361_rx_tx_top.gen/sources_1/ip/clk_wiz_0_4" \
"../../../../../rtl/ad9361_dev_if .v" \
"../../../../../rtl/ad9361_init.v" \
"../../../../../rtl/ad9361_spi.v" \
"../../../../../rtl/ad9361_test_top.v" \
"../../../../ad9361_rx_tx_top.gen/sources_1/ip/clk_wiz_0_4/clk_wiz_0_clk_wiz.v" \
"../../../../ad9361_rx_tx_top.gen/sources_1/ip/clk_wiz_0_4/clk_wiz_0.v" \
"../../../../../rtl/ad9361_lu.v" \
"../../../../../rtl/tb_ad9361_work.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

