######################################################################
#
# File name : ad9361_test_top_wave.do
# Created on: Tue Nov 12 16:39:28 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
