######################################################################
#
# File name : ad9361_test_top_simulate.do
# Created on: Tue Nov 12 16:39:28 +0800 2024
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.ad9361_test_top xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {ad9361_test_top_wave.do}

view wave
view structure
view signals

do {ad9361_test_top.udo}

run 1000ns
